spring:
  application:
        name:virtual-time-capsule
  datasource:
    url: jdbc:postgresql://localhost:5432/${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
            max-file-size: 500MB
            max-request-size: 500MB
jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    org:
      springframework:
        security: DEBUG

timecapsule:
  upload:
    dir: /app/uploads
