version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  java-app:
    volumes:
      - ./.env:/app/.env
      - timecapsule_uploads_data:/app/uploads
    working_dir: /app
    image: my-java-app-image
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      JWT_SECRET: ${JWT_SECRET}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8080:8080"

  angular-frontend:
    build:
      context: ./frontend/virtual-time-capsule-ui
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - java-app

volumes:
  pgdata:
  timecapsule_uploads_data:
    driver: local